deploy-production:
  stage: deploy
  variables:
    KUBECONFIG: /tmp/config
    KUBE_NAMESPACE: $CI_PROJECT_NAME
    REPLICA_MIN: 2
    REPLICA_MAX: 4
    CPU_LIMIT: 250m
    MEM_LIMIT: 250Mi
  tags:
    - production
  before_script:
    - source cicd/shared-scripts/script_permissions.sh
  script:
    - cicd/shared-scripts/check_kube_domain.sh
    - cicd/shared-scripts/install_dependencies.sh
    - echo ${PROD_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context default-context
    - cicd/shared-scripts/check_namespace.sh
    - cicd/shared-scripts/create_secret.sh
    - cicd/shared-scripts/check_prod_ing_cert.sh
    - cicd/deploy/deploy_environment.sh
    - cicd/deploy/persist_environment_url.sh
  environment:
    name: $CI_PROJECT_NAME/production
    url: https://admin.retail-pim.ingka.com
  artifacts:
    paths: [environment_url.txt, cicd/deploy/k8s-manifest.yaml]
  only:
    refs: 
      - tags
    kubernetes: active
  except:
    - branches