deploy-staging:
  stage: deploy
  variables:
    KUBECONFIG: /tmp/config
    REPLICA_MIN: 1
    REPLICA_MAX: 2
    CPU_LIMIT: 250m
    MEM_LIMIT: 250Mi
  tags:
    - dev
  before_script:
    - source cicd/shared-scripts/script_permissions.sh
  script:
    - cicd/shared-scripts/check_kube_domain.sh
    - cicd/shared-scripts/install_dependencies.sh
    - echo ${DEV_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context default-context
    - cicd/shared-scripts/check_namespace.sh
    - cicd/shared-scripts/create_secret.sh
    - cicd/shared-scripts/check_dev_ing_cert.sh
    - cicd/deploy/deploy_environment.sh
    - cicd/deploy/persist_environment_url.sh
  environment:
    name: $CI_PROJECT_NAME/staging
    url: https://staging.admin.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: delete-staging-environment
  artifacts:
    paths: [environment_url.txt, cicd/deploy/k8s-manifest.yaml]
  only:
    refs: 
      - master
    kubernetes: active
  except:
    - tags
