delete-staging-environment:
  stage: cleanup
  variables:
    KUBECONFIG: /tmp/config
    KUBE_NAMESPACE: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    GIT_STRATEGY: none
  tags:
    - dev
  script:
    - apk add -U openssl curl tar gzip bash ca-certificates git
    - curl -sSL -o /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - curl -sSL -O https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk
    - apk add glibc-2.28-r0.apk
    - rm glibc-2.28-r0.apk
    - curl -sSL -o /usr/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl"
    - chmod +x /usr/bin/kubectl
    - kubectl version --client
    - echo ${DEV_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context default-context
    - kubectl delete -f cicd/deploy/k8s-manifest.yaml
  environment:
    name: $CI_PROJECT_NAME/staging
    action: stop
  when: manual
  allow_failure: true
  only:
    refs: 
      - master
    kubernetes: active
  except: 
    - tags
