spring:
    cloud:
        gcp:
            project-id: ingka-cm-api-dev
            sql: {instance-connection-name: 'ingka-cm-api-dev:europe-west3:cm-dev', database-name: postgres}
            trace:
                enabled: true
    datasource:
        username: postgres
        password: cm-dev
        url: jdbc:postgresql://10.7.32.3:5432/postgres?currentSchema=cm_stable
        hikari:
            maximumPoolSize: 2
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate: {jdbc: {database-platform: org.hibernate.dialect.PostgreSQLDialect, lob: {non_contextual_creation: true}}}
    main:
        allow-bean-definition-overriding: true
    profiles: null
    sleuth:
        sampler:
            probability: 1
        web:
            skip-pattern: (^cleanup.*|.+favicon.*)
management:
    endpoints:
        enabled-by-default: false
    endpoint:
        health:
            enabled: true
    server:
        port: 8081
logging:
    level:
        ROOT: ERROR
        com.ingka.rc.centrum: INFO