spring:
  cloud:
    gcp:
     project-id: ingka-cm-api-dev
     sql:
       instance-connection-name: ingka-cm-api-dev:europe-west3:cm-dev
       database-name: postgres
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          database-platform: org.hibernate.dialect.PostgreSQLDialect
          lob:
            non_contextual_creation: true
        ddl-auto: validate
        default_schema: public
  main:
    allow-bean-definition-overriding: true
  profiles:
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
     enabled: true
logging:
  level:
    ROOT: INFO,ERROR